export const testCardData = [
  {
    object: "card",
    id: "dffd3a5f-066b-40c2-99e0-dba1771c899d",
    oracle_id: "c7a6a165-b709-46e0-ae42-6f69a17c0621",
    multiverse_ids: [1327],
    tcgplayer_id: 1332,
    cardmarket_id: 5713,
    name: "Animate Wall",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/dffd3a5f-066b-40c2-99e0-dba1771c899d",
    scryfall_uri: "https://scryfall.com/card/3ed/1/animate-wall?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/d/f/dffd3a5f-066b-40c2-99e0-dba1771c899d.jpg?1559597175",
      normal:
        "https://cards.scryfall.io/normal/front/d/f/dffd3a5f-066b-40c2-99e0-dba1771c899d.jpg?1559597175",
      large:
        "https://cards.scryfall.io/large/front/d/f/dffd3a5f-066b-40c2-99e0-dba1771c899d.jpg?1559597175",
      png: "https://cards.scryfall.io/png/front/d/f/dffd3a5f-066b-40c2-99e0-dba1771c899d.png?1559597175",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/d/f/dffd3a5f-066b-40c2-99e0-dba1771c899d.jpg?1559597175",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/d/f/dffd3a5f-066b-40c2-99e0-dba1771c899d.jpg?1559597175",
    },
    mana_cost: "{W}",
    cmc: 1,
    type_line: "Enchantment — Aura",
    oracle_text:
      "Enchant Wall\nEnchanted Wall can attack as though it didn't have defender.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: ["Enchant"],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/dffd3a5f-066b-40c2-99e0-dba1771c899d/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ac7a6a165-b709-46e0-ae42-6f69a17c0621&unique=prints",
    collector_number: "1",
    digital: false,
    rarity: "rare",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Dan Frazier",
    artist_ids: ["059bba56-5feb-42e4-8c2e-e2f1e6ba11f9"],
    illustration_id: "6757e04d-7bfc-4bdc-9dcb-02059a2d4e60",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 16512,
    penny_rank: 7426,
    prices: {
      usd: "0.94",
      usd_foil: null,
      usd_etched: null,
      eur: "2.00",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1327",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Animate+Wall&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Animate+Wall&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Animate+Wall",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1332?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Animate+Wall&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Animate+Wall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "605e9a62-53e4-4771-9730-56c78237004a",
    oracle_id: "c9ed8b01-959a-47d6-891e-0abbdccf6e4f",
    multiverse_ids: [1328],
    tcgplayer_id: 1334,
    cardmarket_id: 5714,
    name: "Armageddon",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/605e9a62-53e4-4771-9730-56c78237004a",
    scryfall_uri: "https://scryfall.com/card/3ed/2/armageddon?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/6/0/605e9a62-53e4-4771-9730-56c78237004a.jpg?1559596761",
      normal:
        "https://cards.scryfall.io/normal/front/6/0/605e9a62-53e4-4771-9730-56c78237004a.jpg?1559596761",
      large:
        "https://cards.scryfall.io/large/front/6/0/605e9a62-53e4-4771-9730-56c78237004a.jpg?1559596761",
      png: "https://cards.scryfall.io/png/front/6/0/605e9a62-53e4-4771-9730-56c78237004a.png?1559596761",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/6/0/605e9a62-53e4-4771-9730-56c78237004a.jpg?1559596761",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/6/0/605e9a62-53e4-4771-9730-56c78237004a.jpg?1559596761",
    },
    mana_cost: "{3}{W}",
    cmc: 4,
    type_line: "Sorcery",
    oracle_text: "Destroy all lands.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "not_legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/605e9a62-53e4-4771-9730-56c78237004a/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ac9ed8b01-959a-47d6-891e-0abbdccf6e4f&unique=prints",
    collector_number: "2",
    digital: false,
    rarity: "rare",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Jesper Myrfors",
    artist_ids: ["c011318e-8503-48c1-a990-46e50aff48a0"],
    illustration_id: "be2ceead-1cc4-4e3b-8b0d-bb7010b91312",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 2569,
    prices: {
      usd: "10.16",
      usd_foil: null,
      usd_etched: null,
      eur: "6.37",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1328",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Armageddon&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Armageddon&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Armageddon",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1334?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Armageddon&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Armageddon&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "a21b08d4-b43d-4c93-99e7-39dfe83ced91",
    oracle_id: "17fa98cd-ed8f-483f-9525-7e989a82ebb2",
    multiverse_ids: [1329],
    tcgplayer_id: 1340,
    cardmarket_id: 5715,
    name: "Balance",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/a21b08d4-b43d-4c93-99e7-39dfe83ced91",
    scryfall_uri: "https://scryfall.com/card/3ed/3/balance?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/a/2/a21b08d4-b43d-4c93-99e7-39dfe83ced91.jpg?1559596704",
      normal:
        "https://cards.scryfall.io/normal/front/a/2/a21b08d4-b43d-4c93-99e7-39dfe83ced91.jpg?1559596704",
      large:
        "https://cards.scryfall.io/large/front/a/2/a21b08d4-b43d-4c93-99e7-39dfe83ced91.jpg?1559596704",
      png: "https://cards.scryfall.io/png/front/a/2/a21b08d4-b43d-4c93-99e7-39dfe83ced91.png?1559596704",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/a/2/a21b08d4-b43d-4c93-99e7-39dfe83ced91.jpg?1559596704",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/a/2/a21b08d4-b43d-4c93-99e7-39dfe83ced91.jpg?1559596704",
    },
    mana_cost: "{1}{W}",
    cmc: 2,
    type_line: "Sorcery",
    oracle_text:
      "Each player chooses a number of lands they control equal to the number of lands controlled by the player who controls the fewest, then sacrifices the rest. Players discard cards and sacrifice creatures the same way.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "banned",
      pauper: "not_legal",
      vintage: "restricted",
      penny: "not_legal",
      commander: "banned",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "restricted",
      premodern: "banned",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/a21b08d4-b43d-4c93-99e7-39dfe83ced91/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A17fa98cd-ed8f-483f-9525-7e989a82ebb2&unique=prints",
    collector_number: "3",
    digital: false,
    rarity: "rare",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Mark Poole",
    artist_ids: ["bfdeaf09-f915-4058-8e8b-bcac3bc43c33"],
    illustration_id: "e47fbe71-fcea-4aba-9d74-fc6fec8407f7",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    prices: {
      usd: "3.61",
      usd_foil: null,
      usd_etched: null,
      eur: "5.47",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1329",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Balance&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Balance&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Balance",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1340?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Balance&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Balance&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "63e06cd7-9f00-4343-86c2-9f74945193c2",
    oracle_id: "4c81cfb7-8765-4e28-ae33-4287fa9a86cc",
    multiverse_ids: [1330],
    tcgplayer_id: 1343,
    cardmarket_id: 5716,
    name: "Benalish Hero",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/63e06cd7-9f00-4343-86c2-9f74945193c2",
    scryfall_uri:
      "https://scryfall.com/card/3ed/4/benalish-hero?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/6/3/63e06cd7-9f00-4343-86c2-9f74945193c2.jpg?1559597171",
      normal:
        "https://cards.scryfall.io/normal/front/6/3/63e06cd7-9f00-4343-86c2-9f74945193c2.jpg?1559597171",
      large:
        "https://cards.scryfall.io/large/front/6/3/63e06cd7-9f00-4343-86c2-9f74945193c2.jpg?1559597171",
      png: "https://cards.scryfall.io/png/front/6/3/63e06cd7-9f00-4343-86c2-9f74945193c2.png?1559597171",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/6/3/63e06cd7-9f00-4343-86c2-9f74945193c2.jpg?1559597171",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/6/3/63e06cd7-9f00-4343-86c2-9f74945193c2.jpg?1559597171",
    },
    mana_cost: "{W}",
    cmc: 1,
    type_line: "Creature — Human Soldier",
    oracle_text:
      "Banding (Any creatures with banding, and up to one without, can attack in a band. Bands are blocked as a group. If any creatures with banding you control are blocking or being blocked by a creature, you divide that creature's combat damage, not its controller, among any of the creatures it's being blocked by or is blocking.)",
    power: "1",
    toughness: "1",
    colors: ["W"],
    color_identity: ["W"],
    keywords: ["Banding"],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/63e06cd7-9f00-4343-86c2-9f74945193c2/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A4c81cfb7-8765-4e28-ae33-4287fa9a86cc&unique=prints",
    collector_number: "4",
    digital: false,
    rarity: "common",
    flavor_text:
      "Benalia has a complex caste system that changes with the lunar year. No matter what the season, the only caste that cannot be attained by either heredity or money is that of the hero.",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Douglas Shuler",
    artist_ids: ["a9ddb513-51c7-455c-ab8f-5b90aae9f75b"],
    illustration_id: "36cd4598-d058-49f8-b39e-0a5997ca5a42",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 16437,
    penny_rank: 9923,
    prices: {
      usd: "0.21",
      usd_foil: null,
      usd_etched: null,
      eur: "0.02",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1330",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Benalish+Hero&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Benalish+Hero&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Benalish+Hero",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1343?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Benalish+Hero&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Benalish+Hero&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "c5b6b0a4-bda8-422c-bddb-b2a0ba545596",
    oracle_id: "7861ac9b-3024-4935-804c-2ca4c5a46bf4",
    multiverse_ids: [1331],
    tcgplayer_id: 1347,
    cardmarket_id: 5717,
    name: "Black Ward",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/c5b6b0a4-bda8-422c-bddb-b2a0ba545596",
    scryfall_uri: "https://scryfall.com/card/3ed/5/black-ward?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/c/5/c5b6b0a4-bda8-422c-bddb-b2a0ba545596.jpg?1559596604",
      normal:
        "https://cards.scryfall.io/normal/front/c/5/c5b6b0a4-bda8-422c-bddb-b2a0ba545596.jpg?1559596604",
      large:
        "https://cards.scryfall.io/large/front/c/5/c5b6b0a4-bda8-422c-bddb-b2a0ba545596.jpg?1559596604",
      png: "https://cards.scryfall.io/png/front/c/5/c5b6b0a4-bda8-422c-bddb-b2a0ba545596.png?1559596604",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/c/5/c5b6b0a4-bda8-422c-bddb-b2a0ba545596.jpg?1559596604",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/c/5/c5b6b0a4-bda8-422c-bddb-b2a0ba545596.jpg?1559596604",
    },
    mana_cost: "{W}",
    cmc: 1,
    type_line: "Enchantment — Aura",
    oracle_text:
      "Enchant creature\nEnchanted creature has protection from black. This effect doesn't remove Black Ward.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: ["Enchant"],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "not_legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/c5b6b0a4-bda8-422c-bddb-b2a0ba545596/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A7861ac9b-3024-4935-804c-2ca4c5a46bf4&unique=prints",
    collector_number: "5",
    digital: false,
    rarity: "uncommon",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Dan Frazier",
    artist_ids: ["059bba56-5feb-42e4-8c2e-e2f1e6ba11f9"],
    illustration_id: "fc4483fb-9a70-4061-a62c-bc8cd2ba872d",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 15951,
    prices: {
      usd: "0.25",
      usd_foil: null,
      usd_etched: null,
      eur: "0.80",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1331",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Black+Ward&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Black+Ward&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Black+Ward",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1347?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Black+Ward&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Black+Ward&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "f64f6100-c26a-4b22-9fa6-ab3f287a94aa",
    oracle_id: "5c84d8da-2bfb-4618-89a0-7d9ed604e854",
    multiverse_ids: [1332],
    tcgplayer_id: 1348,
    cardmarket_id: 5718,
    name: "Blessing",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/f64f6100-c26a-4b22-9fa6-ab3f287a94aa",
    scryfall_uri: "https://scryfall.com/card/3ed/6/blessing?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/f/6/f64f6100-c26a-4b22-9fa6-ab3f287a94aa.jpg?1559596802",
      normal:
        "https://cards.scryfall.io/normal/front/f/6/f64f6100-c26a-4b22-9fa6-ab3f287a94aa.jpg?1559596802",
      large:
        "https://cards.scryfall.io/large/front/f/6/f64f6100-c26a-4b22-9fa6-ab3f287a94aa.jpg?1559596802",
      png: "https://cards.scryfall.io/png/front/f/6/f64f6100-c26a-4b22-9fa6-ab3f287a94aa.png?1559596802",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/f/6/f64f6100-c26a-4b22-9fa6-ab3f287a94aa.jpg?1559596802",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/f/6/f64f6100-c26a-4b22-9fa6-ab3f287a94aa.jpg?1559596802",
    },
    mana_cost: "{W}{W}",
    cmc: 2,
    type_line: "Enchantment — Aura",
    oracle_text:
      "Enchant creature\n{W}: Enchanted creature gets +1/+1 until end of turn.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: ["Enchant"],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "legal",
      explorer: "not_legal",
      modern: "legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/f64f6100-c26a-4b22-9fa6-ab3f287a94aa/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A5c84d8da-2bfb-4618-89a0-7d9ed604e854&unique=prints",
    collector_number: "6",
    digital: false,
    rarity: "rare",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Julie Baroh",
    artist_ids: ["bba720a4-46b3-493b-8653-8980e6a8c252"],
    illustration_id: "f5f2c5b5-9e9f-4954-9a05-a82cc9589db5",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 16079,
    penny_rank: 8728,
    prices: {
      usd: "2.54",
      usd_foil: null,
      usd_etched: null,
      eur: "1.97",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1332",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Blessing&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Blessing&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Blessing",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1348?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Blessing&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Blessing&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "9b79eaa0-8a15-4828-9ab7-16c2aab5f19f",
    oracle_id: "fc0bf1d0-46a2-4305-ab2e-466d79d60ab2",
    multiverse_ids: [1333],
    tcgplayer_id: 1350,
    cardmarket_id: 5719,
    name: "Blue Ward",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/9b79eaa0-8a15-4828-9ab7-16c2aab5f19f",
    scryfall_uri: "https://scryfall.com/card/3ed/7/blue-ward?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/9/b/9b79eaa0-8a15-4828-9ab7-16c2aab5f19f.jpg?1559596890",
      normal:
        "https://cards.scryfall.io/normal/front/9/b/9b79eaa0-8a15-4828-9ab7-16c2aab5f19f.jpg?1559596890",
      large:
        "https://cards.scryfall.io/large/front/9/b/9b79eaa0-8a15-4828-9ab7-16c2aab5f19f.jpg?1559596890",
      png: "https://cards.scryfall.io/png/front/9/b/9b79eaa0-8a15-4828-9ab7-16c2aab5f19f.png?1559596890",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/9/b/9b79eaa0-8a15-4828-9ab7-16c2aab5f19f.jpg?1559596890",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/9/b/9b79eaa0-8a15-4828-9ab7-16c2aab5f19f.jpg?1559596890",
    },
    mana_cost: "{W}",
    cmc: 1,
    type_line: "Enchantment — Aura",
    oracle_text:
      "Enchant creature\nEnchanted creature has protection from blue. This effect doesn't remove Blue Ward.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: ["Enchant"],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "not_legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/9b79eaa0-8a15-4828-9ab7-16c2aab5f19f/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Afc0bf1d0-46a2-4305-ab2e-466d79d60ab2&unique=prints",
    collector_number: "7",
    digital: false,
    rarity: "uncommon",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Dan Frazier",
    artist_ids: ["059bba56-5feb-42e4-8c2e-e2f1e6ba11f9"],
    illustration_id: "7789a751-594f-40d9-b112-04de97ee4223",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 16203,
    prices: {
      usd: "0.22",
      usd_foil: null,
      usd_etched: null,
      eur: "0.22",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1333",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Blue+Ward&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Blue+Ward&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Blue+Ward",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1350?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Blue+Ward&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Blue+Ward&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "434f2329-ea4c-41ba-ab62-857076d76442",
    oracle_id: "f3179c3c-7e53-44d2-b579-b9e677efe9d9",
    multiverse_ids: [1334],
    tcgplayer_id: 1356,
    cardmarket_id: 5720,
    name: "Castle",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/434f2329-ea4c-41ba-ab62-857076d76442",
    scryfall_uri: "https://scryfall.com/card/3ed/8/castle?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/4/3/434f2329-ea4c-41ba-ab62-857076d76442.jpg?1559596954",
      normal:
        "https://cards.scryfall.io/normal/front/4/3/434f2329-ea4c-41ba-ab62-857076d76442.jpg?1559596954",
      large:
        "https://cards.scryfall.io/large/front/4/3/434f2329-ea4c-41ba-ab62-857076d76442.jpg?1559596954",
      png: "https://cards.scryfall.io/png/front/4/3/434f2329-ea4c-41ba-ab62-857076d76442.png?1559596954",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/4/3/434f2329-ea4c-41ba-ab62-857076d76442.jpg?1559596954",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/4/3/434f2329-ea4c-41ba-ab62-857076d76442.jpg?1559596954",
    },
    mana_cost: "{3}{W}",
    cmc: 4,
    type_line: "Enchantment",
    oracle_text: "Untapped creatures you control get +0/+2.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/434f2329-ea4c-41ba-ab62-857076d76442/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Af3179c3c-7e53-44d2-b579-b9e677efe9d9&unique=prints",
    collector_number: "8",
    digital: false,
    rarity: "uncommon",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Dameon Willich",
    artist_ids: ["606a37b0-9d2d-477b-b679-100bc30b46b3"],
    illustration_id: "bdc5099a-b1d6-46ec-aff5-86e3878ae897",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 12861,
    prices: {
      usd: "0.28",
      usd_foil: null,
      usd_etched: null,
      eur: "0.13",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1334",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Castle&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Castle&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Castle",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1356?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Castle&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Castle&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "c498313d-bb29-4ab9-ab2f-31bdc3d9f78a",
    oracle_id: "7a5a8414-4da4-4dd0-93ae-210d50f4d6f6",
    multiverse_ids: [1335],
    tcgplayer_id: 1360,
    cardmarket_id: 5721,
    name: "Circle of Protection: Black",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/c498313d-bb29-4ab9-ab2f-31bdc3d9f78a",
    scryfall_uri:
      "https://scryfall.com/card/3ed/9/circle-of-protection:-black?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/c/4/c498313d-bb29-4ab9-ab2f-31bdc3d9f78a.jpg?1559596864",
      normal:
        "https://cards.scryfall.io/normal/front/c/4/c498313d-bb29-4ab9-ab2f-31bdc3d9f78a.jpg?1559596864",
      large:
        "https://cards.scryfall.io/large/front/c/4/c498313d-bb29-4ab9-ab2f-31bdc3d9f78a.jpg?1559596864",
      png: "https://cards.scryfall.io/png/front/c/4/c498313d-bb29-4ab9-ab2f-31bdc3d9f78a.png?1559596864",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/c/4/c498313d-bb29-4ab9-ab2f-31bdc3d9f78a.jpg?1559596864",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/c/4/c498313d-bb29-4ab9-ab2f-31bdc3d9f78a.jpg?1559596864",
    },
    mana_cost: "{1}{W}",
    cmc: 2,
    type_line: "Enchantment",
    oracle_text:
      "{1}: The next time a black source of your choice would deal damage to you this turn, prevent that damage.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "legal",
      legacy: "legal",
      pauper: "legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/c498313d-bb29-4ab9-ab2f-31bdc3d9f78a/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A7a5a8414-4da4-4dd0-93ae-210d50f4d6f6&unique=prints",
    collector_number: "9",
    digital: false,
    rarity: "common",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Jesper Myrfors",
    artist_ids: ["c011318e-8503-48c1-a990-46e50aff48a0"],
    illustration_id: "5754c874-9b33-4b64-834b-1babb6eacfc8",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 14935,
    penny_rank: 14075,
    prices: {
      usd: "0.14",
      usd_foil: null,
      usd_etched: null,
      eur: "0.02",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1335",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Circle+of+Protection%3A+Black&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Circle+of+Protection%3A+Black&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Circle+of+Protection%3A+Black",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1360?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Circle+of+Protection%3A+Black&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Circle+of+Protection%3A+Black&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "539809fc-fdeb-4345-a920-37fdb782fdd8",
    oracle_id: "d7572f17-f85d-45c0-ac64-43aac760eafe",
    multiverse_ids: [1336],
    tcgplayer_id: 1361,
    cardmarket_id: 5722,
    name: "Circle of Protection: Blue",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/539809fc-fdeb-4345-a920-37fdb782fdd8",
    scryfall_uri:
      "https://scryfall.com/card/3ed/10/circle-of-protection:-blue?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/5/3/539809fc-fdeb-4345-a920-37fdb782fdd8.jpg?1559596702",
      normal:
        "https://cards.scryfall.io/normal/front/5/3/539809fc-fdeb-4345-a920-37fdb782fdd8.jpg?1559596702",
      large:
        "https://cards.scryfall.io/large/front/5/3/539809fc-fdeb-4345-a920-37fdb782fdd8.jpg?1559596702",
      png: "https://cards.scryfall.io/png/front/5/3/539809fc-fdeb-4345-a920-37fdb782fdd8.png?1559596702",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/5/3/539809fc-fdeb-4345-a920-37fdb782fdd8.jpg?1559596702",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/5/3/539809fc-fdeb-4345-a920-37fdb782fdd8.jpg?1559596702",
    },
    mana_cost: "{1}{W}",
    cmc: 2,
    type_line: "Enchantment",
    oracle_text:
      "{1}: The next time a blue source of your choice would deal damage to you this turn, prevent that damage.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "legal",
      legacy: "legal",
      pauper: "legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/539809fc-fdeb-4345-a920-37fdb782fdd8/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ad7572f17-f85d-45c0-ac64-43aac760eafe&unique=prints",
    collector_number: "10",
    digital: false,
    rarity: "common",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Dameon Willich",
    artist_ids: ["606a37b0-9d2d-477b-b679-100bc30b46b3"],
    illustration_id: "3aa040cf-23a0-4ce0-98b7-a62984238051",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 15974,
    prices: {
      usd: "0.13",
      usd_foil: null,
      usd_etched: null,
      eur: "0.03",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1336",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Circle+of+Protection%3A+Blue&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Circle+of+Protection%3A+Blue&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Circle+of+Protection%3A+Blue",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1361?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Circle+of+Protection%3A+Blue&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Circle+of+Protection%3A+Blue&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "251e0407-b49a-4ee5-83a1-1523ff03a7a7",
    oracle_id: "41b0f347-1398-4778-bf3f-4007d8a77162",
    multiverse_ids: [1337],
    tcgplayer_id: 1362,
    cardmarket_id: 5723,
    name: "Circle of Protection: Green",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/251e0407-b49a-4ee5-83a1-1523ff03a7a7",
    scryfall_uri:
      "https://scryfall.com/card/3ed/11/circle-of-protection:-green?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/2/5/251e0407-b49a-4ee5-83a1-1523ff03a7a7.jpg?1559596861",
      normal:
        "https://cards.scryfall.io/normal/front/2/5/251e0407-b49a-4ee5-83a1-1523ff03a7a7.jpg?1559596861",
      large:
        "https://cards.scryfall.io/large/front/2/5/251e0407-b49a-4ee5-83a1-1523ff03a7a7.jpg?1559596861",
      png: "https://cards.scryfall.io/png/front/2/5/251e0407-b49a-4ee5-83a1-1523ff03a7a7.png?1559596861",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/2/5/251e0407-b49a-4ee5-83a1-1523ff03a7a7.jpg?1559596861",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/2/5/251e0407-b49a-4ee5-83a1-1523ff03a7a7.jpg?1559596861",
    },
    mana_cost: "{1}{W}",
    cmc: 2,
    type_line: "Enchantment",
    oracle_text:
      "{1}: The next time a green source of your choice would deal damage to you this turn, prevent that damage.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "legal",
      legacy: "legal",
      pauper: "legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/251e0407-b49a-4ee5-83a1-1523ff03a7a7/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A41b0f347-1398-4778-bf3f-4007d8a77162&unique=prints",
    collector_number: "11",
    digital: false,
    rarity: "common",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Sandra Everingham",
    artist_ids: ["8a8ac2c8-84c9-4274-9960-a19a97f0bde5"],
    illustration_id: "3826a644-d46a-4800-ae87-382b809a284b",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 15079,
    penny_rank: 14228,
    prices: {
      usd: "0.15",
      usd_foil: null,
      usd_etched: null,
      eur: "0.02",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1337",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Circle+of+Protection%3A+Green&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Circle+of+Protection%3A+Green&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Circle+of+Protection%3A+Green",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1362?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Circle+of+Protection%3A+Green&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Circle+of+Protection%3A+Green&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "b66cadb3-705d-44d3-9277-5d53cd42dae1",
    oracle_id: "df2738fe-9cd1-4347-8808-105fcfde1190",
    multiverse_ids: [1338],
    tcgplayer_id: 1363,
    cardmarket_id: 5724,
    name: "Circle of Protection: Red",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/b66cadb3-705d-44d3-9277-5d53cd42dae1",
    scryfall_uri:
      "https://scryfall.com/card/3ed/12/circle-of-protection:-red?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/b/6/b66cadb3-705d-44d3-9277-5d53cd42dae1.jpg?1559596690",
      normal:
        "https://cards.scryfall.io/normal/front/b/6/b66cadb3-705d-44d3-9277-5d53cd42dae1.jpg?1559596690",
      large:
        "https://cards.scryfall.io/large/front/b/6/b66cadb3-705d-44d3-9277-5d53cd42dae1.jpg?1559596690",
      png: "https://cards.scryfall.io/png/front/b/6/b66cadb3-705d-44d3-9277-5d53cd42dae1.png?1559596690",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/b/6/b66cadb3-705d-44d3-9277-5d53cd42dae1.jpg?1559596690",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/b/6/b66cadb3-705d-44d3-9277-5d53cd42dae1.jpg?1559596690",
    },
    mana_cost: "{1}{W}",
    cmc: 2,
    type_line: "Enchantment",
    oracle_text:
      "{1}: The next time a red source of your choice would deal damage to you this turn, prevent that damage.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "legal",
      legacy: "legal",
      pauper: "legal",
      vintage: "legal",
      penny: "not_legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/b66cadb3-705d-44d3-9277-5d53cd42dae1/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Adf2738fe-9cd1-4347-8808-105fcfde1190&unique=prints",
    collector_number: "12",
    digital: false,
    rarity: "common",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Mark Tedin",
    artist_ids: ["9ee9a9cc-c09e-486f-918b-69f80cbc4188"],
    illustration_id: "f87b0c24-425a-4a80-80e6-8193f46e4730",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 14557,
    prices: {
      usd: "0.17",
      usd_foil: null,
      usd_etched: null,
      eur: "0.35",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1338",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Circle+of+Protection%3A+Red&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Circle+of+Protection%3A+Red&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Circle+of+Protection%3A+Red",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1363?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Circle+of+Protection%3A+Red&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Circle+of+Protection%3A+Red&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "7f113b87-8569-45b2-b644-fb3f4890c2ca",
    oracle_id: "5f46f86a-9779-4ed3-99cb-76a03d380598",
    multiverse_ids: [1339],
    tcgplayer_id: 1364,
    cardmarket_id: 5725,
    name: "Circle of Protection: White",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/7f113b87-8569-45b2-b644-fb3f4890c2ca",
    scryfall_uri:
      "https://scryfall.com/card/3ed/13/circle-of-protection:-white?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/7/f/7f113b87-8569-45b2-b644-fb3f4890c2ca.jpg?1559596863",
      normal:
        "https://cards.scryfall.io/normal/front/7/f/7f113b87-8569-45b2-b644-fb3f4890c2ca.jpg?1559596863",
      large:
        "https://cards.scryfall.io/large/front/7/f/7f113b87-8569-45b2-b644-fb3f4890c2ca.jpg?1559596863",
      png: "https://cards.scryfall.io/png/front/7/f/7f113b87-8569-45b2-b644-fb3f4890c2ca.png?1559596863",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/7/f/7f113b87-8569-45b2-b644-fb3f4890c2ca.jpg?1559596863",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/7/f/7f113b87-8569-45b2-b644-fb3f4890c2ca.jpg?1559596863",
    },
    mana_cost: "{1}{W}",
    cmc: 2,
    type_line: "Enchantment",
    oracle_text:
      "{1}: The next time a white source of your choice would deal damage to you this turn, prevent that damage.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "legal",
      legacy: "legal",
      pauper: "legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/7f113b87-8569-45b2-b644-fb3f4890c2ca/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A5f46f86a-9779-4ed3-99cb-76a03d380598&unique=prints",
    collector_number: "13",
    digital: false,
    rarity: "common",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Douglas Shuler",
    artist_ids: ["a9ddb513-51c7-455c-ab8f-5b90aae9f75b"],
    illustration_id: "ae0196da-97f8-4f48-8430-1d5560ea59ec",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 12125,
    penny_rank: 13228,
    prices: {
      usd: "0.15",
      usd_foil: null,
      usd_etched: null,
      eur: "0.04",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1339",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Circle+of+Protection%3A+White&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Circle+of+Protection%3A+White&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Circle+of+Protection%3A+White",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1364?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Circle+of+Protection%3A+White&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Circle+of+Protection%3A+White&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "70182de2-253f-47d4-ac46-bec4a88b578e",
    oracle_id: "a24e05fb-dffb-4400-b4ca-22fdde45e7a7",
    multiverse_ids: [1340],
    tcgplayer_id: 1371,
    cardmarket_id: 5726,
    name: "Conversion",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/70182de2-253f-47d4-ac46-bec4a88b578e",
    scryfall_uri: "https://scryfall.com/card/3ed/14/conversion?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/7/0/70182de2-253f-47d4-ac46-bec4a88b578e.jpg?1559596700",
      normal:
        "https://cards.scryfall.io/normal/front/7/0/70182de2-253f-47d4-ac46-bec4a88b578e.jpg?1559596700",
      large:
        "https://cards.scryfall.io/large/front/7/0/70182de2-253f-47d4-ac46-bec4a88b578e.jpg?1559596700",
      png: "https://cards.scryfall.io/png/front/7/0/70182de2-253f-47d4-ac46-bec4a88b578e.png?1559596700",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/7/0/70182de2-253f-47d4-ac46-bec4a88b578e.jpg?1559596700",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/7/0/70182de2-253f-47d4-ac46-bec4a88b578e.jpg?1559596700",
    },
    mana_cost: "{2}{W}{W}",
    cmc: 4,
    type_line: "Enchantment",
    oracle_text:
      "At the beginning of your upkeep, sacrifice Conversion unless you pay {W}{W}.\nAll Mountains are Plains.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "not_legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/70182de2-253f-47d4-ac46-bec4a88b578e/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aa24e05fb-dffb-4400-b4ca-22fdde45e7a7&unique=prints",
    collector_number: "14",
    digital: false,
    rarity: "uncommon",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Jesper Myrfors",
    artist_ids: ["c011318e-8503-48c1-a990-46e50aff48a0"],
    illustration_id: "848130dc-24bb-416e-800a-aa7cc7e872b8",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 20414,
    prices: {
      usd: "0.24",
      usd_foil: null,
      usd_etched: null,
      eur: "0.25",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1340",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Conversion&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Conversion&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Conversion",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1371?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Conversion&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Conversion&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "5670c4c0-b8c3-4100-8cd9-c176b29fe01c",
    oracle_id: "4692740f-be90-459f-8d90-c4ae71771595",
    multiverse_ids: [1341],
    name: "Crusade",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/5670c4c0-b8c3-4100-8cd9-c176b29fe01c",
    scryfall_uri: "https://scryfall.com/card/3ed/15/crusade?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/5/6/5670c4c0-b8c3-4100-8cd9-c176b29fe01c.jpg?1559597165",
      normal:
        "https://cards.scryfall.io/normal/front/5/6/5670c4c0-b8c3-4100-8cd9-c176b29fe01c.jpg?1559597165",
      large:
        "https://cards.scryfall.io/large/front/5/6/5670c4c0-b8c3-4100-8cd9-c176b29fe01c.jpg?1559597165",
      png: "https://cards.scryfall.io/png/front/5/6/5670c4c0-b8c3-4100-8cd9-c176b29fe01c.png?1559597165",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/5/6/5670c4c0-b8c3-4100-8cd9-c176b29fe01c.jpg?1559597165",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/5/6/5670c4c0-b8c3-4100-8cd9-c176b29fe01c.jpg?1559597165",
    },
    mana_cost: "{W}{W}",
    cmc: 2,
    type_line: "Enchantment",
    oracle_text: "White creatures get +1/+1.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "banned",
      pauper: "not_legal",
      vintage: "banned",
      penny: "not_legal",
      commander: "banned",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "banned",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/5670c4c0-b8c3-4100-8cd9-c176b29fe01c/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A4692740f-be90-459f-8d90-c4ae71771595&unique=prints",
    collector_number: "15",
    digital: false,
    rarity: "rare",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Mark Poole",
    artist_ids: ["bfdeaf09-f915-4058-8e8b-bcac3bc43c33"],
    illustration_id: "c2406cb0-b3f9-4ba8-88a1-2b5db19b952f",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    content_warning: true,
    prices: {
      usd: null,
      usd_foil: null,
      usd_etched: null,
      eur: null,
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1341",
    },
  },
  {
    object: "card",
    id: "555011ea-f03a-4815-b593-cc5d92bba7bd",
    oracle_id: "0544b707-ec67-43e3-a25d-fd7005ab673d",
    multiverse_ids: [1342],
    tcgplayer_id: 1383,
    cardmarket_id: 5728,
    name: "Death Ward",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/555011ea-f03a-4815-b593-cc5d92bba7bd",
    scryfall_uri: "https://scryfall.com/card/3ed/16/death-ward?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/5/5/555011ea-f03a-4815-b593-cc5d92bba7bd.jpg?1559596959",
      normal:
        "https://cards.scryfall.io/normal/front/5/5/555011ea-f03a-4815-b593-cc5d92bba7bd.jpg?1559596959",
      large:
        "https://cards.scryfall.io/large/front/5/5/555011ea-f03a-4815-b593-cc5d92bba7bd.jpg?1559596959",
      png: "https://cards.scryfall.io/png/front/5/5/555011ea-f03a-4815-b593-cc5d92bba7bd.png?1559596959",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/5/5/555011ea-f03a-4815-b593-cc5d92bba7bd.jpg?1559596959",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/5/5/555011ea-f03a-4815-b593-cc5d92bba7bd.jpg?1559596959",
    },
    mana_cost: "{W}",
    cmc: 1,
    type_line: "Instant",
    oracle_text: "Regenerate target creature.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/555011ea-f03a-4815-b593-cc5d92bba7bd/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A0544b707-ec67-43e3-a25d-fd7005ab673d&unique=prints",
    collector_number: "16",
    digital: false,
    rarity: "common",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Mark Poole",
    artist_ids: ["bfdeaf09-f915-4058-8e8b-bcac3bc43c33"],
    illustration_id: "63c96c56-69b8-41dd-8696-b678a6ebff10",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 15260,
    penny_rank: 2605,
    prices: {
      usd: "0.22",
      usd_foil: null,
      usd_etched: null,
      eur: "0.15",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1342",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Death+Ward&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Death+Ward&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Death+Ward",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1383?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Death+Ward&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Death+Ward&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "41859c6f-1017-42ae-9061-050fe0db9731",
    oracle_id: "a7e97fa9-4b72-4548-b854-5be5f18a6f1a",
    multiverse_ids: [1343],
    tcgplayer_id: 1391,
    cardmarket_id: 5729,
    name: "Disenchant",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/41859c6f-1017-42ae-9061-050fe0db9731",
    scryfall_uri: "https://scryfall.com/card/3ed/17/disenchant?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/4/1/41859c6f-1017-42ae-9061-050fe0db9731.jpg?1559597158",
      normal:
        "https://cards.scryfall.io/normal/front/4/1/41859c6f-1017-42ae-9061-050fe0db9731.jpg?1559597158",
      large:
        "https://cards.scryfall.io/large/front/4/1/41859c6f-1017-42ae-9061-050fe0db9731.jpg?1559597158",
      png: "https://cards.scryfall.io/png/front/4/1/41859c6f-1017-42ae-9061-050fe0db9731.png?1559597158",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/4/1/41859c6f-1017-42ae-9061-050fe0db9731.jpg?1559597158",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/4/1/41859c6f-1017-42ae-9061-050fe0db9731.jpg?1559597158",
    },
    mana_cost: "{1}{W}",
    cmc: 2,
    type_line: "Instant",
    oracle_text: "Destroy target artifact or enchantment.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "legal",
      future: "legal",
      historic: "legal",
      gladiator: "legal",
      pioneer: "legal",
      explorer: "legal",
      modern: "legal",
      legacy: "legal",
      pauper: "legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      brawl: "legal",
      historicbrawl: "legal",
      alchemy: "legal",
      paupercommander: "legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/41859c6f-1017-42ae-9061-050fe0db9731/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aa7e97fa9-4b72-4548-b854-5be5f18a6f1a&unique=prints",
    collector_number: "17",
    digital: false,
    rarity: "common",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Amy Weber",
    artist_ids: ["c1160787-e72e-4f89-b361-c6864f7a4e3a"],
    illustration_id: "e2240317-2d02-4e7f-8392-019f68339e6e",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 771,
    penny_rank: 4284,
    prices: {
      usd: "0.28",
      usd_foil: null,
      usd_etched: null,
      eur: "0.20",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1343",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Disenchant&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Disenchant&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Disenchant",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1391?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Disenchant&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Disenchant&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "23c35f2c-0442-46f3-966b-667bad6e0e27",
    oracle_id: "22647b1a-5a7c-41b5-b820-b2e9f49c7aad",
    multiverse_ids: [1344],
    tcgplayer_id: 1410,
    cardmarket_id: 5730,
    name: "Eye for an Eye",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/23c35f2c-0442-46f3-966b-667bad6e0e27",
    scryfall_uri:
      "https://scryfall.com/card/3ed/18/eye-for-an-eye?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/2/3/23c35f2c-0442-46f3-966b-667bad6e0e27.jpg?1559596705",
      normal:
        "https://cards.scryfall.io/normal/front/2/3/23c35f2c-0442-46f3-966b-667bad6e0e27.jpg?1559596705",
      large:
        "https://cards.scryfall.io/large/front/2/3/23c35f2c-0442-46f3-966b-667bad6e0e27.jpg?1559596705",
      png: "https://cards.scryfall.io/png/front/2/3/23c35f2c-0442-46f3-966b-667bad6e0e27.png?1559596705",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/2/3/23c35f2c-0442-46f3-966b-667bad6e0e27.jpg?1559596705",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/2/3/23c35f2c-0442-46f3-966b-667bad6e0e27.jpg?1559596705",
    },
    mana_cost: "{W}{W}",
    cmc: 2,
    type_line: "Instant",
    oracle_text:
      "The next time a source of your choice would deal damage to you this turn, instead that source deals that much damage to you and Eye for an Eye deals that much damage to that source's controller.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: [],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/23c35f2c-0442-46f3-966b-667bad6e0e27/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A22647b1a-5a7c-41b5-b820-b2e9f49c7aad&unique=prints",
    collector_number: "18",
    digital: false,
    rarity: "rare",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Mark Poole",
    artist_ids: ["bfdeaf09-f915-4058-8e8b-bcac3bc43c33"],
    illustration_id: "d4786c1c-2bf9-4666-9be8-bb707eb97223",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 16902,
    prices: {
      usd: "1.07",
      usd_foil: null,
      usd_etched: null,
      eur: "1.37",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1344",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Eye+for+an+Eye&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Eye+for+an+Eye&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Eye+for+an+Eye",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1410?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Eye+for+an+Eye&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Eye+for+an+Eye&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "75a45b69-1b8d-4b66-a0bf-6142172c7d27",
    oracle_id: "0d71b157-09a0-4fd4-beb9-103117a784ad",
    multiverse_ids: [1345],
    tcgplayer_id: 1411,
    cardmarket_id: 5731,
    name: "Farmstead",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/75a45b69-1b8d-4b66-a0bf-6142172c7d27",
    scryfall_uri: "https://scryfall.com/card/3ed/19/farmstead?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/7/5/75a45b69-1b8d-4b66-a0bf-6142172c7d27.jpg?1559596697",
      normal:
        "https://cards.scryfall.io/normal/front/7/5/75a45b69-1b8d-4b66-a0bf-6142172c7d27.jpg?1559596697",
      large:
        "https://cards.scryfall.io/large/front/7/5/75a45b69-1b8d-4b66-a0bf-6142172c7d27.jpg?1559596697",
      png: "https://cards.scryfall.io/png/front/7/5/75a45b69-1b8d-4b66-a0bf-6142172c7d27.png?1559596697",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/7/5/75a45b69-1b8d-4b66-a0bf-6142172c7d27.jpg?1559596697",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/7/5/75a45b69-1b8d-4b66-a0bf-6142172c7d27.jpg?1559596697",
    },
    mana_cost: "{W}{W}{W}",
    cmc: 3,
    type_line: "Enchantment — Aura",
    oracle_text:
      'Enchant land\nEnchanted land has "At the beginning of your upkeep, you may pay {W}{W}. If you do, you gain 1 life."',
    colors: ["W"],
    color_identity: ["W"],
    keywords: ["Enchant"],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "not_legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "not_legal",
    },
    games: ["paper"],
    reserved: true,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/75a45b69-1b8d-4b66-a0bf-6142172c7d27/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A0d71b157-09a0-4fd4-beb9-103117a784ad&unique=prints",
    collector_number: "19",
    digital: false,
    rarity: "rare",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Mark Poole",
    artist_ids: ["bfdeaf09-f915-4058-8e8b-bcac3bc43c33"],
    illustration_id: "942beb44-8144-446a-a318-e0656948f4bb",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 22199,
    prices: {
      usd: "1.70",
      usd_foil: null,
      usd_etched: null,
      eur: "2.30",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1345",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Farmstead&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Farmstead&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Farmstead",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1411?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Farmstead&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Farmstead&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
  {
    object: "card",
    id: "c1270551-607c-4ef3-88e7-45b4e2445045",
    oracle_id: "727ab7f2-741e-4442-b5cb-e3032549fa87",
    multiverse_ids: [1346],
    tcgplayer_id: 1438,
    cardmarket_id: 5732,
    name: "Green Ward",
    lang: "en",
    released_at: "1994-04-01",
    uri: "https://api.scryfall.com/cards/c1270551-607c-4ef3-88e7-45b4e2445045",
    scryfall_uri: "https://scryfall.com/card/3ed/20/green-ward?utm_source=api",
    layout: "normal",
    highres_image: true,
    image_status: "highres_scan",
    image_uris: {
      small:
        "https://cards.scryfall.io/small/front/c/1/c1270551-607c-4ef3-88e7-45b4e2445045.jpg?1559596929",
      normal:
        "https://cards.scryfall.io/normal/front/c/1/c1270551-607c-4ef3-88e7-45b4e2445045.jpg?1559596929",
      large:
        "https://cards.scryfall.io/large/front/c/1/c1270551-607c-4ef3-88e7-45b4e2445045.jpg?1559596929",
      png: "https://cards.scryfall.io/png/front/c/1/c1270551-607c-4ef3-88e7-45b4e2445045.png?1559596929",
      art_crop:
        "https://cards.scryfall.io/art_crop/front/c/1/c1270551-607c-4ef3-88e7-45b4e2445045.jpg?1559596929",
      border_crop:
        "https://cards.scryfall.io/border_crop/front/c/1/c1270551-607c-4ef3-88e7-45b4e2445045.jpg?1559596929",
    },
    mana_cost: "{W}",
    cmc: 1,
    type_line: "Enchantment — Aura",
    oracle_text:
      "Enchant creature\nEnchanted creature has protection from green. This effect doesn't remove Green Ward.",
    colors: ["W"],
    color_identity: ["W"],
    keywords: ["Enchant"],
    legalities: {
      standard: "not_legal",
      future: "not_legal",
      historic: "not_legal",
      gladiator: "not_legal",
      pioneer: "not_legal",
      explorer: "not_legal",
      modern: "not_legal",
      legacy: "legal",
      pauper: "not_legal",
      vintage: "legal",
      penny: "not_legal",
      commander: "legal",
      brawl: "not_legal",
      historicbrawl: "not_legal",
      alchemy: "not_legal",
      paupercommander: "not_legal",
      duel: "legal",
      oldschool: "legal",
      premodern: "legal",
    },
    games: ["paper"],
    reserved: false,
    foil: false,
    nonfoil: true,
    finishes: ["nonfoil"],
    oversized: false,
    promo: false,
    reprint: true,
    variation: false,
    set_id: "45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set: "3ed",
    set_name: "Revised Edition",
    set_type: "core",
    set_uri:
      "https://api.scryfall.com/sets/45a69797-8adf-468e-a4e1-ba81fd9d66ac",
    set_search_uri:
      "https://api.scryfall.com/cards/search?order=set&q=e%3A3ed&unique=prints",
    scryfall_set_uri: "https://scryfall.com/sets/3ed?utm_source=api",
    rulings_uri:
      "https://api.scryfall.com/cards/c1270551-607c-4ef3-88e7-45b4e2445045/rulings",
    prints_search_uri:
      "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A727ab7f2-741e-4442-b5cb-e3032549fa87&unique=prints",
    collector_number: "20",
    digital: false,
    rarity: "uncommon",
    card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
    artist: "Dan Frazier",
    artist_ids: ["059bba56-5feb-42e4-8c2e-e2f1e6ba11f9"],
    illustration_id: "d0005542-bdf0-4614-96a0-9f3ae22aa9c0",
    border_color: "white",
    frame: "1993",
    full_art: false,
    textless: false,
    booster: true,
    story_spotlight: false,
    edhrec_rank: 16673,
    prices: {
      usd: "0.25",
      usd_foil: null,
      usd_etched: null,
      eur: "0.10",
      eur_foil: null,
      tix: null,
    },
    related_uris: {
      gatherer:
        "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=1346",
      tcgplayer_infinite_articles:
        "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Green+Ward&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      tcgplayer_infinite_decks:
        "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Green+Ward&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      edhrec: "https://edhrec.com/route/?cc=Green+Ward",
    },
    purchase_uris: {
      tcgplayer:
        "https://www.tcgplayer.com/product/1438?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
      cardmarket:
        "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Green+Ward&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
      cardhoarder:
        "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Green+Ward&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
    },
  },
];
